# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'InTheMiddle2' do
    pod 'GoogleMaps', '~> 2.6'
    pod 'GooglePlaces'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InTheMiddle2

  target 'InTheMiddle2Tests' do
    pod 'GoogleMaps', '~> 2.6'
    pod 'GooglePlaces'

  end

  target 'InTheMiddle2UITests' do
    pod 'GoogleMaps', '~> 2.6'
    pod 'GooglePlaces'

  end

end
